name: WakaTime Stats (Image)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    name: Generate WakaTime Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: wakatime.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          
          base: ""
          
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os
          plugin_wakatime_days: 7 
